version: "3"
services:
    centos79_1:
        container_name: centos79_1
        build: .
        ports:
            - "1111:80"
        volumes:
            - "./cent79_1_root:/root"
            - "./utils:/utils"
        tty: true
        stdin_open: true
        privileged: true

    centos79_2:
        container_name: centos79_2
        build: .
        ports:
            - "2222:80"
        volumes:
            - "./cent79_2_root:/root"
        tty: true
        stdin_open: true
        privileged: true
