version: "3"
services:
    centos79_1:
        container_name: centos79_1
        build: .
        ports:
            - "1111:80"
        tty: true
        stdin_open: true
        volumes:
            - ./cent79_1_httpd.conf:/etc/httpd/conf/
    centos79_2:
        container_name: centos79_2
        build: .
        ports:
            - "2222:80"
        tty: true
        stdin_open: true
        volumes:
            - ./ent79_2_httpd.conf:/etc/httpd/conf/
